openapi: 3.0.0
info:
  title: Tender API
  description: API системы тендеров
  version: 0.0.1
servers:
  - url: http://localhost:8000
    description: dev server

paths:
  /api/ping:
    get:
      summary: Проверка доступности сервера
      description: Проверка доступности сервера
      tags:
        - ping
      responses:
        "200":
          description: Сервер доступен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
  /api/tenders/:
    get:
      parameters: 
        - in: query
          name: srv_type
          schema:
            type: string
          description: Тип услуги тендера
          
      summary: Возврщает список тендеров с указанным типом услуг
      description: Возврщает список опубликованных тендеров с указанным типом услуг. Если не указан srv_type, то возвращаются все тендеры.
      tags:
        - tenders
      responses:
        "200":
          description: Тендеры с указанным типом услуг получены
          content:
            application/json:
              schema:
                  type: object
                  description: Тендеры с указанным типом услуг получены
                  properties:
                    tenders:
                      type: array
                      items:
                        $ref: "#/components/schemas/Tender"
                    message:
                      type: string
                      example: "ok"
        "500":
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                type: object
                description: Ошибка на сервере
                properties:
                  tenders:
                    type: array
                    items:
                      $ref: "#/components/schemas/Tender"
                    example: []
                  message:
                    type: string
                    example: "internal error"
  
components:
  schemas:
    Ping:
      type: object
      properties:
        message:
          type: string
    Tender:
      type: object
      required:
        - name
        - description
        - service_type
        - status
        - organization_id
        - creator_username
      properties:
        name:
          type: string
          example: Тендер 1 
        description:
          type: string
          example: Первый тендер
        service_type:
          type: string
          example: Development
        status:
          type: string
          enum:
            - PUBLISHED
            - CREATED
            - CLOSED
          example: PUBLISHED
        organization_id:
          type: integer
          example: 2
        creator_username:
          type: string
          example: sariya23
      
