server_address: 0.0.0.0:8000
postgress_conn: postgres://nikita:1234@localhost:5432/tender
postgres_jdbc_conn: jdbc:postgresql://localhost:5432/tender
postgres_username: nikita
postgres_password: 1234
postgres_host: localhost
postgres_port: 5432
postgres_database: tender